name: go-backend

networks:
  backendnet:
    name: go-backend

services:
  web:
    container_name: "web"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_DB
    ports:
      - 8080:8080
    expose:
      - 8080
    networks:
      - backendnet
    volumes:
      - ./:/app
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    command: ["./wait-for-it.sh", "db:5432", "--", "air"]

  db:
    container_name: "db"
    image: postgres:latest
    ports:
      - 7432:5432
    expose:
      - 5432
    shm_size: 1gb
    networks:
      - backendnet
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U backend -d backend"]
      interval: 10s
      timeout: 5s
      retries: 5
