version: "3.7"

networks:
  backendnet:
    name: go-backend

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    expose:
      - 8080
    networks:
      - backendnet
    volumes:
      - ./:/app
    restart: on-failure
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "7432:5432"
    expose:
      - 5432
    networks:
      - backendnet
    env_file:
      - .env
